WebClient/Controllers/AdministrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace WebClient.Controllers
{
    public class AdministrationController : Controller
    {
        private readonly DataHttpClient _client;
        public AdministrationController(DataHttpClient dataHttpClient)
        {
            this._client = dataHttpClient;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

WebClient/Controllers/ExpiredStockController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace WebClient.Controllers
{
    public class ExpiredStockController : Controller
    {
        private readonly StockHttpClient _client;
        public ExpiredStockController(StockHttpClient stockHttpClient)
        {
            this._client = stockHttpClient;
        }


        public async Task<IActionResult> Index(string status)
        {
            var stockItems = await _client.GetExpiredStockItems();
            return View(stockItems);
        }
    }
}

WebClient/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using WebClient.Models;

namespace WebClient.Controllers
{
    public class OrdersController : Controller
    {
        private readonly OrderHttpClient _client;
        public OrdersController(OrderHttpClient orderHttpClient)
        {
            this._client = orderHttpClient;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string status)
        {
            if (status == "Accepted")
            {
                var deliveryOrders = await _client.GetOrders("Accepted");
                deliveryOrders.AddRange(await _client.GetOrders("Delivered"));
                return View("Delivery", deliveryOrders);
            }

            var orders = await _client.GetOrders(status);

            return View(orders);
        }

        [HttpGet]
        [Route("/[controller]/{id:int}")]
        public async Task<IActionResult> OrderItems(int id)
        {
            var orders = await _client.GetOrders("");
            ViewData["Order"] = orders.First(o => o.orderId == id);

            var orderItems = await _client.GetOrderItems(id);
            orderItems.ForEach(o => o.total = $"{double.Parse(o.unitPrice, NumberStyles.Currency) * o.quantity:C}");
            return View(orderItems);
        }

        [HttpGet("/[controller]/Order")]
        public async Task<IActionResult> Order()
        {
            var products = await _client.GetProducts();
            var workers = await _client.GetWorkers();
            var customers = await _client.GetCustomers();

            ViewData["Products"] = products;
            ViewData["Workers"] = workers;
            ViewData["Customers"] = customers;
            return View(new OrderBaseViewModel());
        }

        [HttpPost("[controller]/Order")]
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> CreateOrder([FromForm] OrderBaseViewModel order)
        {
            if (ModelState.IsValid)
            {
                var result = await _client.CreateOrder(order);
                if (result)
                {
                    return RedirectToAction("Index");
                }
            }

            return RedirectToAction("Order");
        }


        [HttpPost("[controller]/{id}")]
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> UpdateOrder([FromRoute]int id, [FromForm] OrderViewModel order)
        {
            order.orderId = id;
            var result = await _client.UpdateOrder(order);
            if (result) 
            {
                return RedirectToAction("Index");
            }

            return RedirectToAction("OrderItems");
        }
    }
}

WebClient/Controllers/StocksController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using WebClient.Models;

namespace WebClient.Controllers
{
    [Route("[controller]")]
    public class StocksController : Controller
    {
        private readonly StockHttpClient _client;

        public StocksController(StockHttpClient stockHttpClient)
        {
            this._client = stockHttpClient;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var stocks = await _client.GetStocks();
            return View(stocks);
        }

        [HttpGet("{id:int}")]
        public async Task<IActionResult> StockItems(int id)
        {
            var stockItems = await _client.GetStockItems(id);
            return View(stockItems);
        }

        [HttpGet("/[controller]/StockItem")]
        public async Task<IActionResult> StockItem() 
        {
            var products = await _client.GetProducts();
            var workers = await _client.GetWorkers();

            ViewData["Products"] = products;
            ViewData["Workers"] = workers;

            return View(new StockItemBaseViewModel());
        }

        [HttpPost("[controller]/StockItem")]
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> AddStockItem([FromForm] StockItemBaseViewModel stockItem) 
        {
            if (ModelState.IsValid) 
            {
                var result = await _client.CreateStockItem(stockItem);
                if (result)
                {
                    return RedirectToAction("Index");
                }
            }

            var products = await _client.GetProducts();
            var workers = await _client.GetWorkers();

            ViewData["Products"] = products;
            ViewData["Workers"] = workers;

            return RedirectToAction("StockItem");
        }
    }
}

WebClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html xml:lang="en">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>
        Hamster
    </title>
    <link href="/HamsterLogo.ico" rel="shortcut icon" type="image/x-icon" />
    <link href="/lib/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/lib/font-awesome/css/all.min.css" rel="stylesheet" />
</head>
<body>

    <div class="bg-dark text-white p-2" style="background-color: #242E38 !important">
        <div class="container-fluid">
            <div class="row">
                <div class="col navbar-brand">Hamster Stock Manager</div>
                <div class="col-6 text-right">
                </div>
            </div>
        </div>
    </div>
    <div class="row m-0 p-1">
        <div id="categories" class="col-3">
            <a class="btn btn-block btn-outline-secondary"
               onmouseover="this.style.backgroundColor='#FF4C00';"
               onmouseout="this.style.backgroundColor=''"
               asp-action="Index" asp-controller="Stocks">Stocks</a>
            <a class="btn btn-block btn-outline-secondary"
               onmouseover="this.style.backgroundColor='#FF4C00';"
               onmouseout="this.style.backgroundColor=''"
               asp-action="Index" asp-controller="Orders">Orders</a>
            <a class="btn btn-block btn-outline-secondary"
               onmouseover="this.style.backgroundColor='#FF4C00';"
               onmouseout="this.style.backgroundColor=''"
               asp-action="Index" asp-controller="ExpiredStock">Expired Stock</a>
            <a class="btn btn-block btn-outline-secondary"
               style="background-color: #242E38 !important; color: #FFFFFF !important"
               onmouseover="this.style.backgroundColor='#FF4C00';"
               onmouseout="this.style.backgroundColor='#242E38'"
               asp-action="Index" asp-controller="Administration">Administration</a>
        </div>
        <div class="col-9">
            @RenderBody()
        </div>
    </div>
</body>
</html>