WebClient/Controllers/AdministrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace WebClient.Controllers
{
    public class AdministrationController : Controller
    {
        private readonly DataHttpClient _client;
        public AdministrationController(DataHttpClient dataHttpClient)
        {
            this._client = dataHttpClient;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

WebClient/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebClient.Models;

namespace WebClient.Controllers
{
    public class CustomersController : Controller
    {
        private readonly CustomerHttpClient _client;
        public CustomersController(CustomerHttpClient customerHttpClient)
        {
            this._client = customerHttpClient;
        }

        public async Task<IActionResult> Index()
        {
            var customers = await _client.GetCustomers();
            return View(customers);
        }

        [HttpGet("Customer")]
        public IActionResult Customer()
        {
            return View(new CustomerViewModel());
        }

        [HttpPost("[controller]/Customer")]
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> CreateCustomer([FromForm] CustomerViewModel customer)
        {
            if (ModelState.IsValid)
            {
                if (await _client.CreateCustomer(customer))
                {
                    return View("Index", await _client.GetCustomers());
                }
                else
                {
                    ModelState.AddModelError("", "Something went wrong!");
                }
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> UpdateCustomer([FromForm] CustomerViewModel customer)
        {
            if (ModelState.IsValid)
            {
                if (!await _client.UpdateCustomer(customer))
                {
                    ModelState.AddModelError("", "Something went wrong!");
                }
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        [Route("/[controller]/{id:int}")]
        public async Task<IActionResult> DeleteCustomer(int id)
        {
            await _client.DeleteCustomer(id);
            return View("Index", await _client.GetCustomers());
        }
    }
}

WebClient/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebClient.Models;

namespace WebClient.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ProductHttpClient _client;
        public ProductsController(ProductHttpClient productHttpClient)
        {
            this._client = productHttpClient;
        }

        public async Task<IActionResult> Index()
        {
            var products = await _client.GetProducts();
            return View(products);
        }

        [HttpGet("Product")]
        public IActionResult Product()
        {
            return View(new ProductViewModel());
        }

        [HttpPost("[controller]/Product")]
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> CreateProduct([FromForm] ProductViewModel product)
        {
            if (ModelState.IsValid)
            {
                if (await _client.CreateProduct(product))
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Something went wrong!");
                }
            }

            return RedirectToAction("Product");
        }

        [HttpPost]
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> UpdateProduct([FromForm] ProductViewModel product)
        {
            if (ModelState.IsValid)
            {
                if (!await _client.UpdateProduct(product))
                {
                    ModelState.AddModelError("", "Something went wrong!");
                }
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        [Route("/[controller]/{id:int}")]
        public async Task<IActionResult> DeleteProduct(int id)
        {
            await _client.DeleteProduct(id);
            return RedirectToAction("Index");
        }
    }
}

WebClient/Controllers/WorkersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebClient.Models;

namespace WebClient.Controllers
{
    public class WorkersController : Controller
    {
        private readonly WorkerHttpClient _client;

        public WorkersController(WorkerHttpClient workerHttpClient)
        {
            this._client = workerHttpClient;
        }

        public async Task<IActionResult> Index()
        {
            var workers = await _client.GetWorkers();
            return View(workers);
        }

        [HttpGet("Worker")]
        public IActionResult Worker()
        {
            return View(new WorkerViewModel());
        }

        [HttpPost("[controller]/Worker")]
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> CreateWorker([FromForm] WorkerViewModel worker)
        {
            if (ModelState.IsValid)
            {
                if (await _client.CreateWorker(worker))
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Something went wrong!");
                }
            }

            return RedirectToAction("Worker");
        }

        [HttpPost]
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> UpdateWorker([FromForm] WorkerViewModel worker)
        {
            if(ModelState.IsValid)
            {
                if (!await _client.UpdateWorker(worker))
                {
                    ModelState.AddModelError("", "Something went wrong!");
                }
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        [Route("/[controller]/{id:int}")]
        public async Task<IActionResult> DeleteWorker(int id)
        {
            await _client.DeleteWorker(id);
            return RedirectToAction("Index");
        }
    }
}

WebClient/Views/Administration/Index.cshtml
@{ this.Layout = "_Layout"; }
<div class="row">

    <div class="col-md-3 mb-4">
        <div class="card">
            <div class="card-header" style="background-color: #EAC43D !important"></div>
            <a asp-action="Index" asp-controller="Products"
               onmouseover="this.style.backgroundColor='#EAEAEA';"
               onmouseout="this.style.backgroundColor='#FFFFFF'"
               style="border-color: transparent; background-color: #FFFFFF">
                <div class="card-body" style="height: 200px; text-align: center">
                    <h5 class="card-title">Manage Products</h5>
                    <img src="~/Products.png" width="150" height="150">
                </div>
            </a>
        </div>
    </div>
    <div class="col-md-3 mb-4">
        <div class="card">
            <div class="card-header" style="background-color: #2A5C99 !important"></div>
            <a asp-action="Index" asp-controller="Customers"
               onmouseover="this.style.backgroundColor='#EAEAEA';"
               onmouseout="this.style.backgroundColor='#FFFFFF'"
               style="border-color: transparent; background-color: #FFFFFF">
                <div class="card-body" style="height: 200px; text-align: center">
                    <h5 class="card-title">Manage Customers</h5>
                    <img src="~/Customers.png" width="150" height="150">
                </div>
            </a>
        </div>
    </div>
    <div class="col-md-3 mb-4">
        <div class="card">
            <div class="card-header" style="background-color: #A6CD4E !important"></div>
            <a asp-action="Index" asp-controller="Workers"
               onmouseover="this.style.backgroundColor='#EAEAEA';"
               onmouseout="this.style.backgroundColor='#FFFFFF'"
               style="border-color: transparent; background-color: #FFFFFF">
                <div class="card-body" style="height: 200px; text-align: center">
                    <h5 class="card-title">Manage Workers</h5>
                    <img src="~/Workers.png" width="150" height="150">
                </div>
            </a>
        </div>
    </div>
</div>